// data.js - Shared events data for both index.html and admin.html
const sportsEventsData = [
    {
        id: 1,
        title: "Beirut International Marathon",
        category: "Running",
        location: "Beirut",
        date: "Nov 19, 2026",
        time: "7:00 AM",
        image: "https://images.unsplash.com/photo-1552674605-db6ffd8facb5?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "The biggest marathon in Lebanon with thousands of participants from around the world. Choose from full marathon, half marathon, or 10K.",
        registered: 2850,
        capacity: 10000,
        venue: "Martyr's Square",
        exactLocation: "Starting at Martyr's Square, route through Downtown Beirut",
        coordinates: [33.8938, 35.5018],
        price: 50,
        priceType: "premium",
        priceDisplay: "$50"
    },
    {
        id: 2,
        title: "Beirut Basketball Street Tournament",
        category: "Basketball",
        location: "Beirut",
        date: "Dec 5, 2026",
        time: "2:00 PM",
        image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "3x3 street basketball tournament featuring local and international teams. Cash prizes for winners.",
        registered: 42,
        capacity: 64,
        venue: "Zaitunay Bay",
        exactLocation: "Zaitunay Bay Sports Courts, Beirut Waterfront",
        coordinates: [33.8959, 35.4785],
        price: 20,
        priceType: "budget",
        priceDisplay: "$20 per team"
    },
    {
        id: 3,
        title: "Beirut Yoga Festival",
        category: "Yoga",
        location: "Beirut",
        date: "Nov 25, 2026",
        time: "8:00 AM",
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Day-long yoga festival with multiple sessions, workshops, meditation, and wellness activities.",
        registered: 120,
        capacity: 300,
        venue: "Horsh Beirut",
        exactLocation: "Horsh Beirut Public Park",
        coordinates: [33.8708, 35.5089],
        price: 30,
        priceType: "moderate",
        priceDisplay: "$30"
    },
    {
        id: 4,
        title: "Beirut Tennis Open",
        category: "Tennis",
        location: "Beirut",
        date: "Dec 10, 2026",
        time: "9:00 AM",
        image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Annual tennis tournament for amateur and semi-professional players. Multiple categories available.",
        registered: 65,
        capacity: 128,
        venue: "Beirut Tennis Club",
        exactLocation: "Beirut Tennis Club, Rawcheh",
        coordinates: [33.8881, 35.4819],
        price: 40,
        priceType: "moderate",
        priceDisplay: "$40"
    },
    {
        id: 5,
        title: "Tripoli Football Championship",
        category: "Football",
        location: "Tripoli",
        date: "Dec 10, 2026",
        time: "4:00 PM",
        image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "North Lebanon football championship with teams from across the region. Family-friendly event.",
        registered: 320,
        capacity: 1000,
        venue: "Tripoli Municipal Stadium",
        exactLocation: "Al Mina Road, Tripoli",
        coordinates: [34.4367, 35.8497],
        price: 15,
        priceType: "budget",
        priceDisplay: "$15"
    },
    {
        id: 6,
        title: "Tripoli Traditional Wrestling",
        category: "Wrestling",
        location: "Tripoli",
        date: "Nov 30, 2026",
        time: "6:00 PM",
        image: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Traditional Lebanese wrestling competition in Tripoli's old city. Cultural heritage event.",
        registered: 28,
        capacity: 50,
        venue: "Tripoli Citadel Square",
        exactLocation: "Tripoli Citadel, Old City",
        coordinates: [34.4360, 35.8439],
        price: 0,
        priceType: "free",
        priceDisplay: "FREE"
    },
    {
        id: 7,
        title: "Byblos Coastal Run",
        category: "Running",
        location: "Byblos",
        date: "Nov 25, 2026",
        time: "6:30 AM",
        image: "https://images.unsplash.com/photo-1519861531473-920034658307?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Scenic 10K run along the beautiful Byblos coastline. Perfect for beginners and experienced runners.",
        registered: 185,
        capacity: 500,
        venue: "Byblos Harbor",
        exactLocation: "Starting at Byblos Fishing Port",
        coordinates: [34.1191, 35.6497],
        price: 25,
        priceType: "moderate",
        priceDisplay: "$25"
    },
    {
        id: 8,
        title: "Byblos International Fishing",
        category: "Fishing",
        location: "Byblos",
        date: "Dec 2, 2026",
        time: "5:00 AM",
        image: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Deep sea fishing competition with prizes for biggest catch. Equipment provided.",
        registered: 45,
        capacity: 60,
        venue: "Byblos Fishing Port",
        exactLocation: "Byblos Fishing Port, Main Harbor",
        coordinates: [34.1210, 35.6470],
        price: 100,
        priceType: "premium",
        priceDisplay: "$100 per boat"
    },
    {
        id: 9,
        title: "Sidon Beach Volleyball Championship",
        category: "Volleyball",
        location: "Sidon",
        date: "Dec 2, 2026",
        time: "9:00 AM",
        image: "https://images.unsplash.com/photo-1592656094267-764a5c1fe1af?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "2-day beach volleyball tournament at Sidon's public beach. Open to amateur and semi-pro teams.",
        registered: 24,
        capacity: 32,
        venue: "Sidon Public Beach",
        exactLocation: "Sidon Corniche, Public Beach Area",
        coordinates: [33.5631, 35.3689],
        price: 50,
        priceType: "moderate",
        priceDisplay: "$50 per team"
    },
    {
        id: 10,
        title: "Sidon Sea Kayaking Adventure",
        category: "Kayaking",
        location: "Sidon",
        date: "Dec 9, 2026",
        time: "8:00 AM",
        image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Guided sea kayaking tour along Sidon's historic coastline. All equipment provided.",
        registered: 18,
        capacity: 30,
        venue: "Sidon Sea Castle",
        exactLocation: "Sidon Sea Castle Beach",
        coordinates: [33.5650, 35.3700],
        price: 35,
        priceType: "moderate",
        priceDisplay: "$35"
    },
    {
        id: 11,
        title: "Tyre Coastal Triathlon",
        category: "Triathlon",
        location: "Tyre",
        date: "Dec 16, 2026",
        time: "7:00 AM",
        image: "https://images.unsplash.com/photo-1560279966-8ff2f6c7407a?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Swim, bike, run along Tyre's beautiful UNESCO coastline. Sprint and Olympic distances available.",
        registered: 95,
        capacity: 200,
        venue: "Tyre Beach",
        exactLocation: "Tyre Public Beach, Starting Point",
        coordinates: [33.2705, 35.2031],
        price: 75,
        priceType: "premium",
        priceDisplay: "$75"
    },
    {
        id: 12,
        title: "Tyre Traditional Rowing Race",
        category: "Rowing",
        location: "Tyre",
        date: "Dec 3, 2026",
        time: "10:00 AM",
        image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Traditional wooden boat rowing competition in Tyre's harbor. Cultural heritage event.",
        registered: 12,
        capacity: 20,
        venue: "Tyre Fishing Port",
        exactLocation: "Tyre Fishing Port, South Lebanon",
        coordinates: [33.2720, 35.2050],
        price: 0,
        priceType: "free",
        priceDisplay: "FREE to watch"
    },
    {
        id: 13,
        title: "Baalbek Historic Cycling Race",
        category: "Cycling",
        location: "Baalbek",
        date: "Nov 30, 2026",
        time: "8:30 AM",
        image: "https://images.unsplash.com/photo-1486428128344-5413e434ad35?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Cycling race through Baalbek's historic Roman temple routes. Choose from 40km or 80km routes.",
        registered: 85,
        capacity: 150,
        venue: "Baalbek Temples",
        exactLocation: "Starting at Temple of Jupiter, Baalbek",
        coordinates: [34.0058, 36.2181],
        price: 30,
        priceType: "moderate",
        priceDisplay: "$30"
    },
    {
        id: 14,
        title: "Baalbek Horseback Riding Tour",
        category: "Equestrian",
        location: "Baalbek",
        date: "Dec 17, 2026",
        time: "9:00 AM",
        image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Guided horseback riding tour through Baalbek's countryside. Suitable for all skill levels.",
        registered: 15,
        capacity: 25,
        venue: "Baalbek Equestrian Center",
        exactLocation: "Baalbek Equestrian Center, Bekaa Valley",
        coordinates: [34.0100, 36.2200],
        price: 50,
        priceType: "moderate",
        priceDisplay: "$50"
    },
    {
        id: 15,
        title: "Jounieh Paragliding Festival",
        category: "Air Sports",
        location: "Jounieh",
        date: "Dec 3, 2026",
        time: "10:00 AM",
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Annual paragliding festival with competitions and tandem flights over Jounieh Bay.",
        registered: 45,
        capacity: 80,
        venue: "Harissa Mountain",
        exactLocation: "Takeoff from Harissa, Landing at Jounieh Bay",
        coordinates: [33.9808, 35.6175],
        price: 100,
        priceType: "premium",
        priceDisplay: "$100"
    },
    {
        id: 16,
        title: "Jounieh Jet Ski Competition",
        category: "Water Sports",
        location: "Jounieh",
        date: "Dec 10, 2026",
        time: "11:00 AM",
        image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Jet ski racing competition in Jounieh Bay. Multiple speed categories available.",
        registered: 22,
        capacity: 40,
        venue: "Jounieh Bay",
        exactLocation: "Jounieh Bay Waterfront",
        coordinates: [33.9820, 35.6150],
        price: 75,
        priceType: "premium",
        priceDisplay: "$75"
    },
    {
        id: 17,
        title: "Faraya Ski Championship",
        category: "Winter Sports",
        location: "Faraya",
        date: "Dec 20, 2026",
        time: "9:00 AM",
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Ski and snowboard competitions at Lebanon's premier ski resort. Multiple skill levels.",
        registered: 120,
        capacity: 200,
        venue: "Mzaar Ski Resort",
        exactLocation: "Mzaar Ski Resort, Faraya",
        coordinates: [33.9667, 35.8667],
        price: 120,
        priceType: "premium",
        priceDisplay: "$120"
    },
    {
        id: 18,
        title: "Faraya Snowshoeing Adventure",
        category: "Hiking",
        location: "Faraya",
        date: "Dec 27, 2026",
        time: "8:00 AM",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Guided snowshoeing tour through Faraya's winter wonderland. Snowshoes provided.",
        registered: 30,
        capacity: 50,
        venue: "Mzaar Ski Resort",
        exactLocation: "Mzaar Ski Resort Base",
        coordinates: [33.9680, 35.8680],
        price: 40,
        priceType: "moderate",
        priceDisplay: "$40"
    },
    {
        id: 19,
        title: "Zahle Cycling Marathon",
        category: "Cycling",
        location: "Zahle",
        date: "Dec 23, 2026",
        time: "7:00 AM",
        image: "https://images.unsplash.com/photo-1511994717241-8e4e484dfa8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "100km cycling marathon through the Bekaa Valley vineyards. Support stations every 20km.",
        registered: 75,
        capacity: 200,
        venue: "Zahle Main Square",
        exactLocation: "Starting at Al Midan Square, Zahle",
        coordinates: [33.8467, 35.9020],
        price: 35,
        priceType: "moderate",
        priceDisplay: "$35"
    },
    {
        id: 20,
        title: "Batroun Stand-up Paddleboarding",
        category: "Water Sports",
        location: "Batroun",
        date: "Dec 9, 2026",
        time: "8:00 AM",
        image: "https://images.unsplash.com/photo-1584696049838-8a4dac5627b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Stand-up paddleboarding session along Batroun's rocky coast. Instruction provided for beginners.",
        registered: 25,
        capacity: 40,
        venue: "Batroun Beach",
        exactLocation: "Batroun Public Beach",
        coordinates: [34.2553, 35.6578],
        price: 30,
        priceType: "moderate",
        priceDisplay: "$30"
    },
    {
        id: 21,
        title: "Community Football - All Ages",
        category: "Football",
        location: "Beirut",
        date: "Every Saturday",
        time: "3:00 PM",
        image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Weekly community football for all ages and skill levels. Fun, friendly matches.",
        registered: 45,
        capacity: 100,
        venue: "Beirut Sports City",
        exactLocation: "Beirut Sports City Fields",
        coordinates: [33.8760, 35.5200],
        price: 0,
        priceType: "free",
        priceDisplay: "FREE"
    },
    {
        id: 22,
        title: "Sunrise Yoga by the Sea",
        category: "Yoga",
        location: "Byblos",
        date: "Every Sunday",
        time: "6:00 AM",
        image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        description: "Weekly sunrise yoga sessions overlooking the Mediterranean. Mats provided.",
        registered: 35,
        capacity: 60,
        venue: "Byblos Cliffside",
        exactLocation: "Cliffside overlooking Byblos Harbor",
        coordinates: [34.1250, 35.6450],
        price: 10,
        priceType: "budget",
        priceDisplay: "$10"
    }
];